### ISSUE TITLE
This is a suggestion and not an issue

### ISSUE THREAD

**Issue by giggin** [Risenio/fps-utils#1]
This works perfectly, nothing to say about that. 
Is it possible to add a merchant like the broker to the GUI?

**Comment by Risenio** [comment]
That's **not** possible (as far as I know).

Simply because when you try to send contract to any(but few) npc there is a server-side check, if that npc in range or not, If no then contract won't be accepted from server, therefore it won't send a respond to your client => It won't open.

Broker is the one of "few" that doesn't has that check, basically because when you open negotiate window you open a part of the broker, which means you can have access to it from anywhere without any location limitations.
